// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hjikeevfzfswqydduars.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhqaWtlZXZmemZzd3F5ZGR1YXJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU2MTc1MzMsImV4cCI6MjA5MTE5MzUzM30.WrHSDMN5LcKtt6O3_H9jT1zdV9b_0GNficmbozv-N20";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});